/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner sc= new Scanner(System.in);
        System.out.println("Operacion basicas ");
        
        System.out.println("Suma"); //Carlos Quinga
        System.out.println("Ingrese numero 1: ");
        int n1= sc.nextInt();
        System.out.println("Ingrese numero 2: ");
        int n2= sc.nextInt(); 
        
        int suma = n1+n2;
        System.out.println("su suma: " +suma);
        
        System.out.println("DIVISION"); //Bryan Sasig
        System.out.println("Ingrese otro numero : ");
        int n3= sc.nextInt();
        System.out.println("Ingrese otro numero : ");
        int n4= sc.nextInt(); 
        
        int division = n3/n4;
        System.out.println("su division: " +division);

        
        
        System.out.println("MULTIPLICACIÓN"); //Emerson Yanchapanta
        System.out.println("Ingrese otro numero : ");
        int n5= sc.nextInt();
        System.out.println("Ingrese otro numero : ");
        int n6= sc.nextInt(); 
        
        int multiplicacion = n5*n6;
        System.out.println("su multiplicación es : " +multiplicacion);
      
        System.out.println("RESTA"); //Jean Guamangate
        System.out.println("Ingrese otro numero : ");
        int n7= sc.nextInt();
        System.out.println("Ingrese otro numero : ");
        int n8= sc.nextInt(); 
        
        int resta= n7-n8;
        System.out.println("su resta: " +resta);
        
        System.out.println("prueba de cambios"); 
        
        System.out.println("prueba de cambios final");
        
        System.out.println("resta y multiplicacion");//Bryan Sasig
        System.out.println("Ingrese otro numero : ");
        int n10= sc.nextInt();
        System.out.println("Ingrese otro numero : ");
        int n11= sc.nextInt(); 
        System.out.println("Ingrese otro numero : ");
        int n12= sc.nextInt();

        int rest= n10-n11;
        int multi=rest*n12;
        System.out.println("su resultado: " +multi);
        
        
        System.out.println("prueba de cambios final");
        System.out.println("prueba final yo");//bryan sasigS
        
    }
}
